spring.application.name=autopay

bank.aggregator.userid=${BANK_AGRGTR_USERID:}
bank.aggregator.secret=${BANK_AGRGTR_SECRET:}
bank.aggregator.url=${BANK_AGRGTR_BASE_URL:}
bank.aggregator.endpoint=${BANK_AGRGTR_ENDPOINT:}

# Disable Spring Boot Docker Compose lifecycle unless explicitly enabled
spring.docker.compose.enabled=false
